$f = "c:\Users\LUIs CORDOBA\Downloads\zip_69dfea78ae2b8\PANACEA\Configuracion\PanaceaIEWrapper\MainForm.cs"
$lines = [System.IO.File]::ReadAllLines($f)

# Nuevo contenido para case 1 y case 2 (lineas 2212..2258, 0-indexed)
$new = @(
'                    case 1: // Fecha inicio — OS click en campo + SetDate DevExpress',
'                    {',
'                        var rec1 = _ripsRecords[_ripsRecordIndex];',
'                        string fecha1 = string.IsNullOrWhiteSpace(rec1.FechaInicio) ? "01-01-2026" : rec1.FechaInicio;',
'                        // OS click para dar foco al campo de fecha inicio',
'                        string fPos1 = JsInRips(',
'                            "(function(){var el=document.getElementById(''ctl00_ctl00_ContentPlaceHolder1_mainContent_CntFechas_FechaInicialDateEdit_I'');" +',
'                            "if(!el)return ''NF'';var r=el.getBoundingClientRect();" +',
'                            "return Math.round(r.left+(r.width/2||50))+'',''+Math.round(r.top+(r.height/2||8));})()");',
'                        WriteUiLog("RIPS step1 FechaInicio pos: " + fPos1);',
'                        if (fPos1.Contains(",") && !fPos1.StartsWith("NF"))',
'                        {',
'                            try',
'                            {',
'                                string ifrOff1 = GetRipsIframeOffset();',
'                                var pp1 = fPos1.Split('','');',
'                                var ip1 = ifrOff1.Split('','');',
'                                int elX1 = int.Parse(pp1[0].Trim()), elY1 = int.Parse(pp1[1].Trim());',
'                                int ifrX1 = int.Parse(ip1[0].Trim()), ifrY1 = int.Parse(ip1[1].Trim());',
'                                var bPt1 = webBrowser1.PointToScreen(new System.Drawing.Point(0, 0));',
'                                int screenX1 = bPt1.X + ifrX1 + elX1;',
'                                int screenY1 = bPt1.Y + ifrY1 + elY1;',
'                                WriteUiLog("RIPS step1 Click OS FechaInicio en: " + screenX1 + "," + screenY1);',
'                                this.Activate(); webBrowser1.Focus();',
'                                System.Threading.Thread.Sleep(200);',
'                                System.Windows.Forms.Cursor.Position = new System.Drawing.Point(screenX1, screenY1);',
'                                System.Threading.Thread.Sleep(150);',
'                                NativeMouseClick(screenX1, screenY1);',
'                                System.Threading.Thread.Sleep(300);',
'                            }',
'                            catch (Exception ex1c) { WriteUiLog("RIPS step1 click err: " + ex1c.Message); }',
'                        }',
'                        // Escribir fecha via JS (SetDate DevExpress, fallback directo en input)',
'                        string ef1 = EscapeJs(fecha1);',
'                        r = JsInRips(',
'                            "(function(){" +',
'                            "  var dateStr='" + "'" + ef1 + "'" + "';" +',
'                            "  var p=dateStr.split(''-'');" +',
'                            "  var dt=new Date(parseInt(p[2]),parseInt(p[1])-1,parseInt(p[0]));" +',
'                            "  var c=window[''ctl00_ctl00_ContentPlaceHolder1_mainContent_CntFechas_FechaInicialDateEdit''];" +',
'                            "  if(c&&c.SetDate){c.SetDate(dt);return ''SET_OK'';}" +',
'                            "  var inp=document.getElementById(''ctl00_ctl00_ContentPlaceHolder1_mainContent_CntFechas_FechaInicialDateEdit_I'');" +',
'                            "  if(!inp)return ''NF'';inp.value=dateStr;" +',
'                            "  try{inp.fireEvent(''onchange'');}catch(ex){}try{inp.fireEvent(''onblur'');}catch(ex){}" +',
'                            "  return ''DIRECT:''+inp.value;" +',
'                            "})()");',
'                        WriteUiLog("RIPS step1 FechaInicio: " + r);',
'                        _ripsStep++;',
'                        timer.Interval = 800;',
'                        break;',
'                    }',
'',
'                    case 2: // Fecha fin — OS click en campo + SetDate DevExpress',
'                    {',
'                        var rec2 = _ripsRecords[_ripsRecordIndex];',
'                        string fecha2 = string.IsNullOrWhiteSpace(rec2.FechaFin) ? "30-04-2026" : rec2.FechaFin;',
'                        // OS click para dar foco al campo de fecha fin',
'                        string fPos2 = JsInRips(',
'                            "(function(){var el=document.getElementById(''ctl00_ctl00_ContentPlaceHolder1_mainContent_CntFechas_FechaFinalDateEdit_I'');" +',
'                            "if(!el)return ''NF'';var r=el.getBoundingClientRect();" +',
'                            "return Math.round(r.left+(r.width/2||50))+'',''+Math.round(r.top+(r.height/2||8));})()");',
'                        WriteUiLog("RIPS step2 FechaFin pos: " + fPos2);',
'                        if (fPos2.Contains(",") && !fPos2.StartsWith("NF"))',
'                        {',
'                            try',
'                            {',
'                                string ifrOff2 = GetRipsIframeOffset();',
'                                var pp2 = fPos2.Split('','');',
'                                var ip2 = ifrOff2.Split('','');',
'                                int elX2 = int.Parse(pp2[0].Trim()), elY2 = int.Parse(pp2[1].Trim());',
'                                int ifrX2 = int.Parse(ip2[0].Trim()), ifrY2 = int.Parse(ip2[1].Trim());',
'                                var bPt2 = webBrowser1.PointToScreen(new System.Drawing.Point(0, 0));',
'                                int screenX2 = bPt2.X + ifrX2 + elX2;',
'                                int screenY2 = bPt2.Y + ifrY2 + elY2;',
'                                WriteUiLog("RIPS step2 Click OS FechaFin en: " + screenX2 + "," + screenY2);',
'                                this.Activate(); webBrowser1.Focus();',
'                                System.Threading.Thread.Sleep(200);',
'                                System.Windows.Forms.Cursor.Position = new System.Drawing.Point(screenX2, screenY2);',
'                                System.Threading.Thread.Sleep(150);',
'                                NativeMouseClick(screenX2, screenY2);',
'                                System.Threading.Thread.Sleep(300);',
'                            }',
'                            catch (Exception ex2c) { WriteUiLog("RIPS step2 click err: " + ex2c.Message); }',
'                        }',
'                        // Escribir fecha via JS (SetDate DevExpress, fallback directo en input)',
'                        string ef2 = EscapeJs(fecha2);',
'                        r = JsInRips(',
'                            "(function(){" +',
'                            "  var dateStr='" + "'" + ef2 + "'" + "';" +',
'                            "  var p=dateStr.split(''-'');" +',
'                            "  var dt=new Date(parseInt(p[2]),parseInt(p[1])-1,parseInt(p[0]));" +',
'                            "  var c=window[''ctl00_ctl00_ContentPlaceHolder1_mainContent_CntFechas_FechaFinalDateEdit''];" +',
'                            "  if(c&&c.SetDate){c.SetDate(dt);return ''SET_OK'';}" +',
'                            "  var inp=document.getElementById(''ctl00_ctl00_ContentPlaceHolder1_mainContent_CntFechas_FechaFinalDateEdit_I'');" +',
'                            "  if(!inp)return ''NF'';inp.value=dateStr;" +',
'                            "  try{inp.fireEvent(''onchange'');}catch(ex){}try{inp.fireEvent(''onblur'');}catch(ex){}" +',
'                            "  return ''DIRECT:''+inp.value;" +',
'                            "})()");',
'                        WriteUiLog("RIPS step2 FechaFin: " + r);',
'                        _ripsStep++;',
'                        timer.Interval = 800;',
'                        break;',
'                    }'
)

# Reemplazar lineas 2212..2258 con el nuevo contenido
$before = $lines[0..2211]
$after  = $lines[2259..($lines.Count-1)]
$result = $before + $new + $after

[System.IO.File]::WriteAllLines($f, $result, [System.Text.Encoding]::UTF8)
Write-Host "OK: $($result.Count) lineas escritas"
